# Generated by Django 6.0.5 on 2026-05-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionmedia',
            name='exif_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
