# Generated by Django 6.0.5 on 2026-05-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_exif_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
