# Generated by Django 6.0.5 on 2026-05-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_season_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='keep_image_exif',
            field=models.BooleanField(default=False),
        ),
    ]
