# Generated by Django 6.0.5 on 2026-05-11 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0005_remove_is_private_and_require_join_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='season',
            name='keep_image_exif',
        ),
        migrations.RemoveField(
            model_name='season',
            name='starts_at',
        ),
    ]
