# Generated by Django 6.0.5 on 2026-05-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0006_remove_exif_and_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=64),
        ),
    ]
