# Generated by Django 6.0.5 on 2026-05-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0007_season_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=16),
        ),
    ]
