# Generated by Django 6.0.5 on 2026-05-10 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quest_type', models.CharField(choices=[('photo', 'Photo'), ('text', 'Text'), ('video', 'Video'), ('location', 'Location'), ('mixed', 'Mixed')], default='mixed', max_length=16)),
                ('default_duration_seconds', models.PositiveIntegerField(default=120)),
                ('default_points_max', models.PositiveSmallIntegerField(default=5)),
                ('default_media_rules_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_override', models.CharField(blank=True, max_length=200)),
                ('description_override', models.TextField(blank=True)),
                ('quest_mode', models.CharField(choices=[('scheduled', 'Scheduled'), ('open', 'Open')], default='open', max_length=16)),
                ('assignment_policy', models.CharField(choices=[('host_assigned', 'Host Assigned'), ('open_claim', 'Open Claim')], default='open_claim', max_length=20)),
                ('entry_policy', models.CharField(choices=[('code_required', 'Code Required'), ('scan_and_go', 'Scan And Go')], default='scan_and_go', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting', 'Waiting'), ('live', 'Live'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('start_mode', models.CharField(default='admin_triggered', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=120)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('reveal_policy', models.CharField(choices=[('instant', 'Instant'), ('after_close', 'After Close'), ('end_of_event', 'End Of Event')], default='instant', max_length=20)),
                ('points_max', models.PositiveSmallIntegerField(default=5)),
                ('allow_late_submissions', models.BooleanField(default=False)),
                ('late_grace_seconds', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quests', to='seasons.seasonparticipant')),
                ('quest_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season_quests', to='quests.questtemplate')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='seasons.season')),
            ],
        ),
        migrations.CreateModel(
            name='QuestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('scored', 'Scored'), ('missed', 'Missed'), ('excused', 'Excused')], default='pending', max_length=16)),
                ('assignment_source', models.CharField(choices=[('host_assigned', 'Host Assigned'), ('open_claim', 'Open Claim'), ('qr_scan', 'QR Scan'), ('rsvp_code', 'RSVP Code')], default='open_claim', max_length=20)),
                ('submission_due_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_assignments', to='seasons.seasonparticipant')),
                ('season_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quests.seasonquest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='seasonquest',
            constraint=models.UniqueConstraint(fields=('season', 'display_order'), name='season_display_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='questassignment',
            constraint=models.UniqueConstraint(fields=('season_quest', 'participant'), name='season_quest_participant_unique'),
        ),
    ]
