# Generated by Django 6.0.5 on 2026-05-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonquest',
            name='rsvp_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
