# Generated by Django 6.0.5 on 2026-05-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_remove_seasonquest_display_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='quest_type',
        ),
        migrations.AlterField(
            model_name='seasonquest',
            name='reveal_policy',
            field=models.CharField(choices=[('instant', 'Instant'), ('after_close', 'End Of Quest'), ('end_of_event', 'End Of Season')], default='instant', max_length=20),
        ),
    ]
