# Generated by Django 6.0.5 on 2026-05-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0006_remove_quest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonquest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('complete', 'Complete'), ('archived', 'Archived')], default='draft', max_length=16),
        ),
    ]
