# Generated by Django 6.0.5 on 2026-05-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0008_normalize_seasonquest_status_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonquest',
            name='quest_mode',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('open', 'Drop-in')], default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='seasonquest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('complete', 'Closed'), ('archived', 'Archived')], default='draft', max_length=16),
        ),
    ]
